# Note: ClickHouse scaling is more complex due to sharding
# This HPA will scale replicas within each shard
# To add more shards, you need to modify the ClickHouseInstallation CRD

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: clickhouse-cluster-hpa
  namespace: clickhouse
  annotations:
    # ClickHouse scaling requires careful coordination
    autoscaling.alpha.kubernetes.io/conditions: |
      [
        {
          "type": "ScalingLimited",
          "status": "False",
          "reason": "DesiredWithinRange"
        }
      ]
spec:
  scaleTargetRef:
    apiVersion: clickhouse.altinity.com/v1
    kind: ClickHouseInstallation
    name: clickhouse-cluster
  minReplicas: 4  # 2 shards x 2 replicas (minimum)
  maxReplicas: 8  # 2 shards x 4 replicas (maximum)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # 10 min - very cautious with ClickHouse
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300  # Scale down 1 pod every 5 min
    scaleUp:
      stabilizationWindowSeconds: 180  # 3 min
      policies:
        - type: Pods
          value: 2  # Add 2 pods at a time (1 per shard ideally)
          periodSeconds: 60
