apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerdb-server
  namespace: peerdb
  labels:
    app: peerdb
    component: server
spec:
  replicas: 1  # Reduced for resource constraints
  selector:
    matchLabels:
      app: peerdb
      component: server
  template:
    metadata:
      labels:
        app: peerdb
        component: server
    spec:
      # Node affinity - Deploy only on peerdb nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - peerdb

      # Tolerations for peerdb nodes
      tolerations:
        - key: workload
          operator: Equal
          value: peerdb
          effect: NoSchedule

      containers:
        - name: peerdb-server
          image: ghcr.io/peerdb-io/peerdb-server:stable-v0.34.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9900
              protocol: TCP
            - name: grpc
              containerPort: 8080
              protocol: TCP
          env:
            - name: PEERDB_CATALOG_HOST
              value: "peerdb-postgresql"
            - name: PEERDB_CATALOG_PORT
              value: "5432"
            - name: PEERDB_CATALOG_USER
              value: "peerdb"
            - name: PEERDB_CATALOG_PASSWORD
              value: "peerdb123"
            - name: PEERDB_CATALOG_DATABASE
              value: "peerdb_metadata"
            - name: TEMPORAL_HOST_PORT
              value: "peerdb-temporal-frontend:7233"
            - name: PEERDB_ENABLE_MIRROR_ROUTES
              value: "true"
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerdb-flow-api
  namespace: peerdb
  labels:
    app: peerdb
    component: flow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peerdb
      component: flow-api
  template:
    metadata:
      labels:
        app: peerdb
        component: flow-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - peerdb
      tolerations:
        - key: workload
          operator: Equal
          value: peerdb
          effect: NoSchedule
      containers:
        - name: flow-api
          image: ghcr.io/peerdb-io/flow-api:stable-v0.34.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 8112
              protocol: TCP
            - name: http
              containerPort: 8113
              protocol: TCP
          env:
            - name: PEERDB_CATALOG_HOST
              value: "peerdb-postgresql"
            - name: PEERDB_CATALOG_PORT
              value: "5432"
            - name: PEERDB_CATALOG_USER
              value: "peerdb"
            - name: PEERDB_CATALOG_PASSWORD
              value: "peerdb123"
            - name: PEERDB_CATALOG_DATABASE
              value: "peerdb_metadata"
            - name: TEMPORAL_HOST_PORT
              value: "peerdb-temporal-frontend:7233"
            - name: AWS_SDK_LOAD_CONFIG
              value: "false"
            - name: AWS_EC2_METADATA_DISABLED
              value: "true"
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerdb-flow-worker
  namespace: peerdb
  labels:
    app: peerdb
    component: flow-worker
spec:
  replicas: 1  # Reduced for resource constraints
  selector:
    matchLabels:
      app: peerdb
      component: flow-worker
  template:
    metadata:
      labels:
        app: peerdb
        component: flow-worker
    spec:
      # Node affinity - Deploy only on peerdb nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - peerdb

      # Tolerations for peerdb nodes
      tolerations:
        - key: workload
          operator: Equal
          value: peerdb
          effect: NoSchedule

      containers:
        - name: flow-worker
          image: ghcr.io/peerdb-io/flow-worker:stable-v0.34.2
          imagePullPolicy: IfNotPresent
          env:
            - name: PEERDB_CATALOG_HOST
              value: "peerdb-postgresql"
            - name: PEERDB_CATALOG_PORT
              value: "5432"
            - name: PEERDB_CATALOG_USER
              value: "peerdb"
            - name: PEERDB_CATALOG_PASSWORD
              value: "peerdb123"
            - name: PEERDB_CATALOG_DATABASE
              value: "peerdb_metadata"
            - name: TEMPORAL_HOST_PORT
              value: "peerdb-temporal-frontend:7233"
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
---
# PeerDB Flow Snapshot Worker
# Handles initial snapshot tasks on snapshot-flow-task-queue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerdb-flow-snapshot-worker
  namespace: peerdb
  labels:
    app: peerdb
    component: flow-snapshot-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peerdb
      component: flow-snapshot-worker
  template:
    metadata:
      labels:
        app: peerdb
        component: flow-snapshot-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - peerdb
      tolerations:
        - key: workload
          operator: Equal
          value: peerdb
          effect: NoSchedule
      containers:
        - name: flow-snapshot-worker
          image: ghcr.io/peerdb-io/flow-snapshot-worker:stable-v0.34.2
          imagePullPolicy: IfNotPresent
          env:
            - name: PEERDB_CATALOG_HOST
              value: "peerdb-postgresql"
            - name: PEERDB_CATALOG_PORT
              value: "5432"
            - name: PEERDB_CATALOG_USER
              value: "peerdb"
            - name: PEERDB_CATALOG_PASSWORD
              value: "peerdb123"
            - name: PEERDB_CATALOG_DATABASE
              value: "peerdb_metadata"
            - name: TEMPORAL_HOST_PORT
              value: "peerdb-temporal-frontend:7233"
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 250m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerdb-ui
  namespace: peerdb
  labels:
    app: peerdb
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peerdb
      component: ui
  template:
    metadata:
      labels:
        app: peerdb
        component: ui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - peerdb
      tolerations:
        - key: workload
          operator: Equal
          value: peerdb
          effect: NoSchedule
      containers:
        - name: peerdb-ui
          image: ghcr.io/peerdb-io/peerdb-ui:stable-v0.34.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: PEERDB_FLOW_SERVER_HTTP
              value: "http://peerdb-flow-api:8113"
            - name: DATABASE_URL
              value: "postgres://peerdb:peerdb123@peerdb-postgresql:5432/peerdb_metadata"
            - name: PEERDB_PASSWORD
              value: "peerdb"
            - name: NEXTAUTH_SECRET
              value: "peerdb-secret-key-change-in-production"
            - name: NEXTAUTH_URL
              value: "http://localhost:3000"
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
