apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerdb-server
  namespace: peerdb
  labels:
    app: peerdb
    component: server
spec:
  replicas: 1  # Reduced for resource constraints
  selector:
    matchLabels:
      app: peerdb
      component: server
  template:
    metadata:
      labels:
        app: peerdb
        component: server
    spec:
      # Node affinity - Deploy only on peerdb nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - peerdb

      # Tolerations for peerdb nodes
      tolerations:
        - key: workload
          operator: Equal
          value: peerdb
          effect: NoSchedule

      containers:
        - name: peerdb-server
          image: ghcr.io/peerdb-io/peerdb-server:stable-v0.34.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9900
              protocol: TCP
            - name: grpc
              containerPort: 8080
              protocol: TCP
          env:
            - name: PEERDB_CATALOG_HOST
              value: "peerdb-postgresql"
            - name: PEERDB_CATALOG_PORT
              value: "5432"
            - name: PEERDB_CATALOG_USER
              value: "peerdb"
            - name: PEERDB_CATALOG_PASSWORD
              value: "peerdb123"
            - name: PEERDB_CATALOG_DATABASE
              value: "peerdb_metadata"
            - name: TEMPORAL_HOST_PORT
              value: "peerdb-temporal-frontend:7233"
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerdb-flow-worker
  namespace: peerdb
  labels:
    app: peerdb
    component: flow-worker
spec:
  replicas: 1  # Reduced for resource constraints
  selector:
    matchLabels:
      app: peerdb
      component: flow-worker
  template:
    metadata:
      labels:
        app: peerdb
        component: flow-worker
    spec:
      # Node affinity - Deploy only on peerdb nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - peerdb

      # Tolerations for peerdb nodes
      tolerations:
        - key: workload
          operator: Equal
          value: peerdb
          effect: NoSchedule

      containers:
        - name: flow-worker
          image: ghcr.io/peerdb-io/flow-worker:stable-v0.34.2
          imagePullPolicy: IfNotPresent
          env:
            - name: PEERDB_CATALOG_HOST
              value: "peerdb-postgresql"
            - name: PEERDB_CATALOG_PORT
              value: "5432"
            - name: PEERDB_CATALOG_USER
              value: "peerdb"
            - name: PEERDB_CATALOG_PASSWORD
              value: "peerdb123"
            - name: PEERDB_CATALOG_DATABASE
              value: "peerdb_metadata"
            - name: TEMPORAL_HOST_PORT
              value: "peerdb-temporal-frontend:7233"
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
