apiVersion: v1
kind: Service
metadata:
  name: peerdb-server
  namespace: peerdb
  labels:
    app: peerdb
    component: server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9900
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 8080
      targetPort: grpc
      protocol: TCP
  selector:
    app: peerdb
    component: server
