# Job to create default Temporal namespace
# Required for PeerDB flow-worker to function
apiVersion: batch/v1
kind: Job
metadata:
  name: temporal-create-default-namespace
  namespace: peerdb
  labels:
    app: peerdb
    component: temporal-setup
spec:
  ttlSecondsAfterFinished: 86400  # 24 hours
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: peerdb
        component: temporal-setup
    spec:
      restartPolicy: OnFailure

      # Node affinity - Deploy only on peerdb nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - peerdb

      # Tolerations for peerdb nodes
      tolerations:
        - key: workload
          operator: Equal
          value: peerdb
          effect: NoSchedule

      containers:
        - name: create-namespace
          image: temporalio/admin-tools:1.25.0-tctl-1.18.1-cli-1.0.0
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Waiting for Temporal frontend to be ready..."
              until tctl cluster health 2>/dev/null; do
                echo "  Temporal not ready yet, waiting..."
                sleep 5
              done

              echo "Temporal is ready! Checking if 'default' namespace exists..."
              if tctl namespace describe default 2>/dev/null; then
                echo "'default' namespace already exists, nothing to do."
              else
                echo "Creating 'default' namespace..."
                tctl namespace register default
                echo "'default' namespace created successfully!"
              fi
          env:
            - name: TEMPORAL_CLI_ADDRESS
              value: "peerdb-temporal-frontend:7233"
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m
