apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
  namespace: minio
spec:
  ttlSecondsAfterFinished: 86400
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: minio-setup
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mc
        image: minio/mc:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for MinIO to be ready..."
          until mc alias set myminio http://minio.minio.svc.cluster.local:9000 minioadmin minioadmin; do
            echo "Waiting for MinIO..."
            sleep 5
          done

          echo "Creating bucket 'peerdb-staging'..."
          mc mb myminio/peerdb-staging --ignore-existing

          echo "Setting public policy for bucket..."
          mc anonymous set public myminio/peerdb-staging

          echo "Bucket created successfully!"
          mc ls myminio/
