apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-crds
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy CRDs before everything
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/chalkan3/zapper-argocd.git
    targetRevision: main
    path: manifests/cloudnative-pg
    directory:
      include: pooler-crd.yaml

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - Replace=true  # Replace existing CRDs if needed
