apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: peerdb-setup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/chalkan3/zapper-argocd.git
    targetRevision: main
    path: manifests/peerdb
    directory:
      include: setup-mirror-job.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: peerdb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
