# ClickHouse Cluster Configuration
# Este arquivo será aplicado como um manifest adicional via ArgoCD

apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse-cluster
  namespace: clickhouse
spec:
  configuration:
    users:
      admin/password: admin123
      admin/networks/ip:
        - "0.0.0.0/0"
      admin/profile: default
      admin/quota: default

      # Read-only user for monitoring
      readonly/password: readonly123
      readonly/networks/ip:
        - "0.0.0.0/0"
      readonly/profile: readonly
      readonly/quota: default

    # User profiles - simplified for basic setup
    profiles:
      default/max_memory_usage: "10000000000"
      default/max_execution_time: "300"
      default/readonly: "0"
      default/allow_ddl: "1"

      readonly/max_memory_usage: "5000000000"
      readonly/max_execution_time: "60"
      readonly/readonly: "1"
      readonly/allow_ddl: "0"

    # Global settings - only server-level settings
    settings:
      max_concurrent_queries: "100"
      max_connections: "4096"

    # Cluster with 2 shards, no replication (no keeper needed)
    clusters:
      - name: "main-cluster"
        layout:
          shardsCount: 2
          replicasCount: 1

  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume
      logVolumeClaimTemplate: log-volume
      serviceTemplate: service-template
      podTemplate: clickhouse-pod-template

  templates:
    podTemplates:
      - name: clickhouse-pod-template
        spec:
          # Node affinity - Deploy only on clickhouse nodes
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: workload
                        operator: In
                        values:
                          - clickhouse

          # Tolerations for clickhouse nodes
          tolerations:
            - key: workload
              operator: Equal
              value: clickhouse
              effect: NoSchedule

          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:24.3
              resources:
                requests:
                  memory: "256Mi"    # MINIMAL
                  cpu: "100m"        # MINIMAL
                limits:
                  memory: "512Mi"    # MINIMAL
                  cpu: "500m"        # MINIMAL

              # Liveness probe
              livenessProbe:
                httpGet:
                  path: /ping
                  port: 8123
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 3

              # Readiness probe
              readinessProbe:
                httpGet:
                  path: /ping
                  port: 8123
                initialDelaySeconds: 10
                periodSeconds: 5
                timeoutSeconds: 3
                failureThreshold: 3

    volumeClaimTemplates:
      - name: data-volume
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path  # K3s default storage class
          resources:
            requests:
              storage: 5Gi   # MINIMAL

      - name: log-volume
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi   # MINIMAL

    serviceTemplates:
      - name: service-template
        spec:
          ports:
            - name: http
              port: 8123
              targetPort: 8123
            - name: native
              port: 9000
              targetPort: 9000
          type: ClusterIP
---
# Removed ClickHouseKeeperInstallation and service - using simple single-node cluster
# Can be upgraded to replicated cluster with keeper later if needed
