# PostgreSQL Cluster Configuration
# Este arquivo será aplicado como um manifest adicional via ArgoCD

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: cloudnative-pg
spec:
  instances: 3

  # Node affinity - Deploy only on postgres nodes
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload
                operator: In
                values:
                  - postgres

  # Tolerations for postgres nodes
  tolerations:
    - key: workload
      operator: Equal
      value: postgres
      effect: NoSchedule

  # PostgreSQL configuration for CDC
  postgresql:
    parameters:
      wal_level: "logical"
      max_wal_senders: "10"
      max_replication_slots: "10"
      max_connections: "200"

  # Storage configuration
  storage:
    size: 20Gi

  # Resources for HPA
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

  # Bootstrap - Create schema only (data seeded by Job)
  bootstrap:
    initdb:
      database: app_db
      owner: app_user
      secret:
        name: postgres-cluster-app
      postInitSQL:
        # Create tables with proper schema
        - CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            username VARCHAR(50) UNIQUE NOT NULL,
            email VARCHAR(100) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );
        - CREATE TABLE IF NOT EXISTS orders (
            id SERIAL PRIMARY KEY,
            user_id INTEGER REFERENCES users(id),
            product_name VARCHAR(100) NOT NULL,
            quantity INTEGER NOT NULL,
            price DECIMAL(10,2) NOT NULL,
            status VARCHAR(20) DEFAULT 'pending',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );
        - CREATE TABLE IF NOT EXISTS events (
            id SERIAL PRIMARY KEY,
            event_type VARCHAR(50) NOT NULL,
            user_id INTEGER REFERENCES users(id),
            metadata JSONB,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );

        # Configure REPLICA IDENTITY FULL for CDC
        - ALTER TABLE users REPLICA IDENTITY FULL;
        - ALTER TABLE orders REPLICA IDENTITY FULL;
        - ALTER TABLE events REPLICA IDENTITY FULL;

        # Note: Test data is seeded by the postgres-seed-data Job
        # See: manifests/cloudnative-pg/seed-data-job.yaml

  # Monitoring
  monitoring:
    enablePodMonitor: false
